import {
  Box,
  chakra,
  Container,
  Divider,
  Flex,
  Icon,
  Image,
  Stack,
  Tag,
  TagLabel,
  TagRightIcon,
} from '@chakra-ui/react'
import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { VscGithubInverted, VscMail, VscTwitter } from 'react-icons/vsc'

import { NextChakraAnchor } from '@/components/NextChakraAnchor'
import { Item } from '@/features/article'
import { client } from '@/libs/client'

type Props = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async () => {
  const data = await client.get<{ contents: { id: string; title: string; body: string }[] }>({
    endpoint: 'articles',
  })
  return {
    props: {
      articles: data.contents,
    },
  }
}

const Page: NextPage<Props> = ({ articles }) => {
  return (
    <Container maxW="container.lg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction={{ base: 'column', md: 'row' }} gridGap="2">
        <Stack bg="gray.200" p="4" spacing="6" w={{ base: 'full', md: 1 / 3 }}>
          <Box>
            <Image
              borderRadius="full"
              boxSize="100px"
              src="https://cdn.pixabay.com/photo/2020/09/17/14/08/kangaroo-5579255_1280.jpg"
              alt="pocketech"
              fit="cover"
            />
            <chakra.h1 fontSize="2xl" mt="6">
              <Link href="/">
                <a>ポケットにファンタジー</a>
              </Link>
            </chakra.h1>
          </Box>
          <chakra.p>
            Next.jsとTypeScriptが好きなエンジニア一年生です。好きなお菓子はカプリコです。
          </chakra.p>
          <Flex gridGap="6">
            <a href="#" target="_blank">
              <Icon as={VscTwitter} w={8} h={8} color="gray.600" />
            </a>
            <a href="#" target="_blank">
              <Icon as={VscGithubInverted} w={8} h={8} color="gray.600" />
            </a>
            <a href="#" target="_blank">
              <Icon as={VscMail} w={8} h={8} color="gray.600" />
            </a>
          </Flex>
          <nav>
            <Stack as="ul" listStyleType="none">
              <li>
                <NextChakraAnchor href="/articles"> Articles</NextChakraAnchor>
              </li>
              <li>
                <NextChakraAnchor href="/works"> Works</NextChakraAnchor>
              </li>
              <li>
                <NextChakraAnchor href="/contacts"> Privacy Policy</NextChakraAnchor>
              </li>
            </Stack>
          </nav>
          <chakra.p>タグ</chakra.p>
          <Stack spacing={4}>
            {['sm', 'md', 'lg'].map((size) => (
              <Tag size={size} key={size} variant="outline" colorScheme="blue">
                <TagLabel>Blue</TagLabel>
                <TagRightIcon as={VscTwitter} />
              </Tag>
            ))}
          </Stack>
        </Stack>
        <Divider orientation="vertical" display={{ base: 'none', md: 'block' }} />
        <Box bg="green" flexGrow={1}>
          <Stack spacing={4} as="ul" listStyleType="none">
            {articles.map((article) => (
              <chakra.li key={article.id}>
                <Item
                  body={article.body}
                  title={article.title}
                  date="2021/1/1"
                  tag="マガジン"
                  id={article.id}
                />
              </chakra.li>
            ))}
          </Stack>
        </Box>
      </Flex>
    </Container>
  )
}

export default Page
